services:
  db:
    image: supabase/postgres:15.1.0.117
    container_name: supabase-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  studio:
    image: supabase/studio:latest
    container_name: supabase-studio
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: postgres

  kong:
    image: kong:2.8.1
    container_name: supabase-kong
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
    volumes:
      - ./volumes/api:/var/lib/kong
      - ./volumes/kong.yml:/var/lib/kong/kong.yml

  auth:
    image: supabase/gotrue:v2.82.4
    container_name: supabase-auth
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_JWT_SECRET: "your-super-secret-jwt-token-with-at-least-32-characters-long"
      GOTRUE_JWT_EXP: 3600
    depends_on:
      - db

  rest:
    image: postgrest/postgrest:v10.1.2
    container_name: supabase-rest
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: "your-super-secret-jwt-token-with-at-least-32-characters-long"
    depends_on:
      - db

  storage:
    image: supabase/storage-api:v0.40.4
    container_name: supabase-storage
    environment:
      ANON_KEY: "your-super-secret-jwt-token-with-at-least-32-characters-long"
      SERVICE_KEY: "your-super-secret-jwt-token-with-at-least-32-characters-long"
      PROJECT_REF: "bjwdssmqcnupfcfvdgju"
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: "your-super-secret-jwt-token-with-at-least-32-characters-long"
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      PGREST_URL: http://rest:3000
      STORAGE_BACKEND: file
      FILE_SIZE_LIMIT: 52428800
      GLOBAL_S3_BUCKET: supa-storage-testing
      REGION: ap-southeast-2
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    volumes:
      - storage-data:/var/lib/storage
    depends_on:
      - db
      - rest

volumes:
  db-data:
  storage-data:
