name = "applocation"
compatibility_date = "2023-08-23"
send_metrics = false
account_id = "a9e4229fffc596d7229c7efbedd7925f"

[[d1_databases]]
binding = "DATABASE"
database_name = "applocation-dev-db"
database_id = "93ad6a03-f0d4-4768-a2bd-bc51a00725c4"
