name = "applocation"
compatibility_date = "2024-08-08"
send_metrics = false
main = "src/worker.ts"
account_id = "a9e4229fffc596d7229c7efbedd7925f"

[env.dev]
name = "applocation-dev"
workers_dev = true

[env.production]
name = "applocation"
route = "app.t4stack.com/*"
workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "PROD_APPLOCATE"
database_id = "e1d875bc-9d83-409f-acca-2a0c8f4c6d93"
